#!/bin/bash

# to compile GCC, these three libraries may have to be fetched:

wget http://www.mpfr.org/mpfr-current/mpfr-3.1.2.tar.xz
wget http://www.multiprecision.org/mpc/download/mpc-1.0.tar.gz
wget ftp://ftp.gmplib.org/pub/gmp/gmp-5.1.3.tar.bz2

# and, according to instructions in 
#   http://gcc.gnu.org/install/prerequisites.html
# expand the tarballs into the directory with GCC sources, change their
# directory names to mpfr mpc gmp (removing the version suffixes);
# these libraries are then compiled along with GCC

# OTOH, if you are lucky, the libraries installed by aptitude will do...

# fetch all the auxiliary programs -- this assumes a Debian installation
aptitude install make flex bison libgmp-dev libmpfr-dev libmpc-dev g++
unset ls
umask 022

# check the latest version of GCC in http://ftp.gnu.org/gnu/gcc/
# check the latest version of binutils in http://ftp.gnu.org/gnu/binutils

BINUTILS=binutils-2.23.2
COMPILER=gcc-4.8.2

wget -c http://ftp.gnu.org/gnu/binutils/${BINUTILS}.tar.bz2
wget -c http://ftp.gnu.org/gnu/gcc/${COMPILER}/${COMPILER}.tar.gz

# set the installation pathname as PREFIX so that {bin,lib,man} are put there
#   make sure you have write permission to /opt/cross,
#   else perform the "make install" steps as root (with umask 022)
export PREFIX=/opt/cross/
export TARGET=mips

tar -xvjf ${BINUTILS}.tar.bz2
cd ${BINUTILS}
./configure --target=$TARGET --prefix=$PREFIX --disable-nls
make
# do the next one as root?  sudo umask 022 ; make install
make install
cd ..

tar -xvzf ${COMPILER}.tar.gz
cd ${COMPILER}
# you may want/need to expand the libraries' tarballs at this point
export PATH=$PATH:$PREFIX/bin
./configure --target=$TARGET --prefix=$PREFIX --disable-nls \
     --enable-languages=c,c++ --without-headers
make all-gcc
# do the next one as root?  sudo umask 022 ; make install-gcc
make install-gcc
cd ..

